name: Run the Action on each commit
on:
  push:
    branches:
      - master
jobs: 
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - run: echo "Running!"
